/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import DataAccess.BoreHole;
import DataAccess.BoreholesTable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

/**
 *
 * @author Dave
 */
public class Boreholes extends javax.swing.JFrame {

    BoreholesTable boreholestable;

    /**
     * Creates new form WaterLevels
     */
    public Boreholes() {
        initComponents();
        displayJtable();
         int BoreholeTypeID = 0;
        txtName.setText(tblBoreholes.getValueAt(0, 0).toString());
        String Type = tblBoreholes.getValueAt(0, 1).toString();
        switch (Type) {

            case "Auger-Hole":
                BoreholeTypeID = 0;
                break;

            case "Shot-Hole":
                BoreholeTypeID = 1;
                break;

            case "Well":
                BoreholeTypeID = 2;
                break;

            case "Vibracore":
                BoreholeTypeID = 3;
                break;

        }
        cmbType.setSelectedIndex(BoreholeTypeID);
        txtLatitude.setText(tblBoreholes.getValueAt(0, 2).toString());
        txtLongitude.setText(tblBoreholes.getValueAt(0, 3).toString());
        txtElevation.setText((tblBoreholes.getValueAt(0, 4).toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLatitude = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLongitude = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtElevation = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoreholes = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnViewTypes = new javax.swing.JButton();
        btnViewWaterLevels = new javax.swing.JButton();
        btnSortAlpha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BOREHOLE MANAGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(307, 307, 307))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Name");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Type");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Latitude");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Longitude");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Elevation");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auger-Hole", "Shot-Hole", "Well", "Vibracore" }));

        tblBoreholes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBoreholes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoreholesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBoreholes);

        btnInsert.setText("Add New Borehole");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update Borehole");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Borehole");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnViewTypes.setText("View Borehole Types");
        btnViewTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTypesActionPerformed(evt);
            }
        });

        btnViewWaterLevels.setText("View Water Levels");
        btnViewWaterLevels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewWaterLevelsActionPerformed(evt);
            }
        });

        btnSortAlpha.setText("Sort Boreholes Alphabetically");
        btnSortAlpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortAlphaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbType, 0, 146, Short.MAX_VALUE)
                                .addComponent(txtName)
                                .addComponent(txtLatitude)
                                .addComponent(txtLongitude))
                            .addComponent(txtElevation, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnInsert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnViewTypes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewWaterLevels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSortAlpha, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnViewTypes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewWaterLevels)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSortAlpha))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtElevation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTypesActionPerformed
        BoreholeTypes bht = new BoreholeTypes();
        bht.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewTypesActionPerformed

    private void btnViewWaterLevelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewWaterLevelsActionPerformed
        WaterLevels wl = new WaterLevels();
        wl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewWaterLevelsActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed

        String boreholeName = txtName.getText();
        int boreholeTypeID = cmbType.getSelectedIndex();
        String BoreholeType = null;
        switch (boreholeTypeID) {

            case 0:
                BoreholeType = "Auger-Hole";
                break;

            case 1:
                BoreholeType = "Shot-Hole";
                break;

            case 2:
                BoreholeType = "Well";
                break;

            case 3:
                BoreholeType = "Vibracore";
                break;

        }
        String boreholeLatitude = txtLatitude.getText();
        String boreholeLongitude = txtLongitude.getText();
        float boreholeElevation = Float.parseFloat(txtElevation.getText());

        BoreHole borehole = new BoreHole(boreholeName, BoreholeType, boreholeLatitude, boreholeLongitude, boreholeElevation);

        BoreHole.addNewBorehole(borehole);
        displayJtable();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String boreholeName = txtName.getText();
        int boreholeTypeID = cmbType.getSelectedIndex();
        String BoreholeType = null;
        switch (boreholeTypeID) {

            case 0:
                BoreholeType = "Auger-Hole";
                break;

            case 1:
                BoreholeType = "Shot-Hole";
                break;

            case 2:
                BoreholeType = "Well";
                break;

            case 3:
                BoreholeType = "Vibracore";
                break;

        }
        String boreholeLatitude = txtLatitude.getText();
        String boreholeLongitude = txtLongitude.getText();
        float boreholeElevation = Float.parseFloat(txtElevation.getText());

        BoreHole borehole = new BoreHole(boreholeName, BoreholeType, boreholeLatitude, boreholeLongitude, boreholeElevation);

        BoreHole.updateBorehole(borehole);
        displayJtable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblBoreholesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoreholesMouseClicked
         int BoreholeTypeID = 0;
        txtName.setText(tblBoreholes.getValueAt(tblBoreholes.getSelectedRow(), 0).toString());
        String Type = tblBoreholes.getValueAt(tblBoreholes.getSelectedRow(), 1).toString();
        switch (Type) {

            case "Auger-Hole":
                BoreholeTypeID = 0;
                break;

            case "Shot-Hole":
                BoreholeTypeID = 1;
                break;

            case "Well":
                BoreholeTypeID = 2;
                break;

            case "Vibracore":
                BoreholeTypeID = 3;
                break;

        }
        cmbType.setSelectedIndex(BoreholeTypeID);
        txtLatitude.setText(tblBoreholes.getValueAt(tblBoreholes.getSelectedRow(), 2).toString());
        txtLongitude.setText(tblBoreholes.getValueAt(tblBoreholes.getSelectedRow(), 3).toString());
        txtElevation.setText((tblBoreholes.getValueAt(tblBoreholes.getSelectedRow(), 4).toString()));
    }//GEN-LAST:event_tblBoreholesMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int ID = Integer.parseInt(tblBoreholes.getValueAt(tblBoreholes.getSelectedRow(), 5).toString());
         BoreHole bh = new BoreHole();
         bh.deleteBorehole(ID);
         displayJtable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSortAlphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortAlphaActionPerformed
       displayJtableAlphabetically();
    }//GEN-LAST:event_btnSortAlphaActionPerformed

    private void displayJtable() {

        List<BoreHole> borehole_list = new ArrayList<>();
        BoreHole bh = new BoreHole();
        borehole_list = bh.getAllBoreholes();

        boreholestable = new BoreholesTable(borehole_list);
        tblBoreholes.setModel(boreholestable);

    }
    
    private void displayJtableAlphabetically() {

        List<BoreHole> borehole_list = new ArrayList<>();
        BoreHole bh = new BoreHole();
        borehole_list = bh.getAllBoreholes();
        
        Collections.sort(borehole_list, new SortByName());

        boreholestable = new BoreholesTable(borehole_list);
        tblBoreholes.setModel(boreholestable);
    }
    
    public static class SortByName implements Comparator<BoreHole> {

        @Override
        public int compare(BoreHole o1, BoreHole o2) {
            return o1.getBoreholeName().compareTo(o2.getBoreholeName());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boreholes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boreholes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boreholes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boreholes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boreholes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSortAlpha;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewTypes;
    private javax.swing.JButton btnViewWaterLevels;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBoreholes;
    private javax.swing.JTextField txtElevation;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
